#!/bin/bash

#update meteor packages and possibly patches
meteor update --all-packages && meteor update --patch

#setup the iptables to route port 3000 to port 80
sudo iptables -A PREROUTING -t nat -i eth0 -p tcp --dport 80 -j REDIRECT --to-port 3000

#run meteor verbose
meteor --settings settings.json -v
